// <auto-generated />
using KarolWronaEFProducts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KarolWronaEFProducts.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20220426185600_v3")]
    partial class v3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("InvoiceProduct", b =>
                {
                    b.Property<int>("CanBeSoldInInvoiceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IncludesProductID")
                        .HasColumnType("INTEGER");

                    b.HasKey("CanBeSoldInInvoiceNumber", "IncludesProductID");

                    b.HasIndex("IncludesProductID");

                    b.ToTable("InvoiceProduct");
                });

            modelBuilder.Entity("KarolWronaEFProducts.Invoice", b =>
                {
                    b.Property<int>("InvoiceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("InvoiceNumber");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("KarolWronaEFProducts.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SuppliedBySupplierID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitsOnStock")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductID");

                    b.HasIndex("SuppliedBySupplierID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("KarolWronaEFProducts.Supplier", b =>
                {
                    b.Property<int>("SupplierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .HasColumnType("TEXT");

                    b.HasKey("SupplierID");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("InvoiceProduct", b =>
                {
                    b.HasOne("KarolWronaEFProducts.Invoice", null)
                        .WithMany()
                        .HasForeignKey("CanBeSoldInInvoiceNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KarolWronaEFProducts.Product", null)
                        .WithMany()
                        .HasForeignKey("IncludesProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KarolWronaEFProducts.Product", b =>
                {
                    b.HasOne("KarolWronaEFProducts.Supplier", "SuppliedBy")
                        .WithMany("Supplies")
                        .HasForeignKey("SuppliedBySupplierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SuppliedBy");
                });

            modelBuilder.Entity("KarolWronaEFProducts.Supplier", b =>
                {
                    b.Navigation("Supplies");
                });
#pragma warning restore 612, 618
        }
    }
}
